config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('findby.urls')),
    path('admin/', admin.site.urls)
]

findby/urls.py
from django.urls import path

from . import views

app_name = 'findby'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/product', views.search_product, name='search_product'),
    path('delete/products', views.delete_products, name='delete_products'),
]

findby/models.py
from datetime import datetime

from django.db import models

from findby.schemas import ProductDto


# Create your models here.

class Product(models.Model):
    name: str = models.CharField(max_length=50, null=True)
    category: str = models.CharField(max_length=50, null=True)
    price: str = models.CharField(max_length=50, null=True)
    brand: str = models.CharField(max_length=50, null=True)
    link: str = models.CharField(max_length=255, null=True)
    create_date: datetime = models.DateTimeField(auto_now_add=True)
    modify_date: datetime = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

    def from_dto(self, dto: ProductDto):
        self.name = dto.name
        self.category = dto.category
        self.price = dto.price
        self.brand = dto.brand
        self.link = dto.link
        return self

findby/views.py
from typing import Union, List

from django.core.paginator import Paginator
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect

from findby.form import SearchProductForm, DeleteProductIdsForm
from findby.models import Product
from findby.simp_crawling import simp_crawling


# Create your views here.
def index(request: HttpRequest) -> HttpResponse:
    page: Union[str, None] = request.GET.get('page')
    search_category: Union[str, None] = request.GET.get('search_category')

    products = Product.objects.all().order_by('-create_date')
    if search_category:
        products = products.filter(category=search_category)
    context = __set_index_page_products_context(products, page, search_category)

    return render(request, 'findby/products.html', context)


def search_product(request: HttpRequest) -> HttpResponse:
    form = SearchProductForm(request.POST)
    if form.is_valid():
        product_dto = simp_crawling(words=form.cleaned_data['contents'], category=form.cleaned_data['category'])
        product = Product().from_dto(dto=product_dto)
        product.save()

    return redirect('findby:index')


def delete_products(request):
    form = DeleteProductIdsForm(request.POST)
    if form.is_valid():
        product_ids: [] = form.cleaned_data['selected_products'].split(',')
        Product.objects.filter(id__in=product_ids).delete()

    return redirect('findby:index')


def __set_index_page_products_context(products: List[Product], page: Union[str, None], search_category: str) -> dict:
    paginator: Paginator = Paginator(products, 10)  # page당 10개씩 보여주기
    page_obj: Paginator = paginator.get_page(page)
    return {
        'products': page_obj,
        'search_category': search_category
    }

templates/base.html
{% load static %}
<!Doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- findby CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>find kream product</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용을 작성 -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 마침 -->
<!-- bootstrap js -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/findby/products.html
{% extends 'base.html' %}
{% load findby_filter %}
{% block content %}
    <div class="mt-5 mb-3 mx-3">
        <h3 class="mx-auto">신규 상품 등록</h3>
    </div>
    <div class="container d-flex justify-content-between" style="max-width: 100%">
        <div class="d-flex">
            <form method="post" action="{% url 'findby:search_product' %}"
                  class="row row-cols-lg-auto g-1 align-items-center">
                {% csrf_token %}
                {% if form.errors %}
                    <div>
                        {% for field in form %}
                            {% if field.errors %}
                                <div>
                                    <strong>{{ field.label }}</strong>
                                    {{ field.errors }}
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="col-auto text-center">
                    <label class="visually-hidden" for="category">카테고리</label>
                    <select class="form-select" id="category" name="category">
                        <option value="">category</option>
                        <option value="신발">신발</option>
                        <option value="상의">상의</option>
                        <option value="하의">하의</option>
                        <option value="잡화">잡화</option>
                    </select>
                </div>

                <div class="col-auto">
                    <label for="contents" class="visually-hidden">검색 : </label>
                    <input name="contents" type="text" class="form-control" id="contents" placeholder="검색어를 입력하세요">
                </div>
                <div class="col-auto">
                    <input type="submit" value="조회" class="btn btn-primary" role="button">
                </div>
            </form>
            <div class="col-auto">
                <form id="deleteForm" method="post" action="{% url 'findby:delete_products' %}">
                    {% csrf_token %}
                    <input type="hidden" name="selected_products" id="selected_products">
                    <input type="button" class="btn btn-danger" value="선택된 상품 삭제" role="button" onclick="submitForm()">
                </form>
            </div>

        </div>

        <div class="d-flex align-items-center">
            <div>
                <span>테이블 분리 :</span>
            </div>
            <div>
                <form method="get" action="{% url 'findby:index' %}" id="search_category_form">
                    <label class="visually-hidden" for="search_category">카테고리</label>
                    <select class="form-select" id="search_category" name="search_category">
                        <option value=""
                                {% if not search_category or search_category == "" %}selected{% endif %}>
                            카테고리
                        </option>
                        <option value="신발" {% if search_category == "신발" %}selected{% endif %}>신발</option>
                        <option value="상의" {% if search_category == "상의" %}selected{% endif %}>상의</option>
                        <option value="하의" {% if search_category == "하의" %}selected{% endif %}>하의</option>
                        <option value="잡화" {% if search_category == "잡화" %}selected{% endif %}>잡화</option>
                    </select>
                </form>
            </div>
        </div>
    </div>


    <div class="container my-3 mx-auto" style="max-width: 100%">
        <table class="table">
            <thead>
            <tr class="text-center">
                <th></th>
                <th>no</th>
                <th>category</th>
                <th>brand</th>
                <th>product_name</th>
                <th>price</th>
            </tr>
            </thead>
            <tbody>
            {% if products %}
                {% for product in products %}
                    <tr class="text-center">
                        <td style="width: 5%">
                            <label for="select_product_id_list">
                                <input type="checkbox" name="select_product_id_list" value="{{ product.id }}"
                                       class="selectCheckbox">
                            </label>
                        </td>
                        <td style="width: 10%">
                            <!-- 상훔 번호 = 전체 건수 - 시작 인덱스 - 현재 인덱스 + 1 -->
                            {{ products.paginator.count|sub:products.start_index|sub:forloop.counter0|add:1 }}
                        </td>
                        <td style="width: 15%">{{ product.category }}</td>
                        <td style="width: 10%">{{ product.brand }}</td> <!-- 글쓴이 추가 -->
                        <td style="width: 50%">
                            <a href="{{ product.link }}" target="_blank">{{ product.name }}</a>
                        </td>
                        <td style="width: 15%">{{ product.price }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="5"> 조회목록이 없습니다.</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
        <!-- 페이지 네이션 -->
        <ul class="pagination justify-content-center">
            <!-- 이전 페이지 -->
            {% if products.has_previous %}
                <li class="page-item">
                    <a class="page-link"
                       href="?{% if search_category %}search_category={{ search_category }}&{% endif %}page={{ products.previous_page_number }}">이전</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
            {% endif %}
            <!-- 페이지 리스트 -->
            {% for page_number in products.paginator.page_range %}
                {% if page_number >= products.number|add:-5 and page_number <= products.number|add:5 %}
                    {% if page_number == products.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link"
                               href="?{% if search_category %}search_category={{ search_category }}&{% endif %}page={{ page_number }}">{{ page_number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link"
                               href="?{% if search_category %}search_category={{ search_category }}&{% endif %}page={{ page_number }}">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            <!-- 다음 페이지 -->
            {% if products.has_next %}
                <li class="page-item">
                    <a class="page-link"
                       href="?{% if search_category %}search_category={{ search_category }}&{% endif %}page={{ products.next_page_number }}">다음</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
            {% endif %}
        </ul>
        <!-- 페이지 네이션 끝 -->
    </div>

    <script>
        const selectForm = document.getElementById("search_category_form");
        selectForm.addEventListener("change", () => {
            selectForm.submit()
        });

        function submitForm() {
            let selectedProducts = [];
            const checkboxes = document.querySelectorAll('.selectCheckbox:checked');

            checkboxes.forEach(function (checkbox) {
                selectedProducts.push(checkbox.value);
            });

            document.getElementById('selected_products').value = selectedProducts.join(',');
            document.getElementById('deleteForm').submit();
        }
    </script>
{% endblock %}

templates/navbar.html
<!-- navigation bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'findby:index' %}">Find-By</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li>
                    <a class="nav-link" href="https://github.com/sunsik17">
                        <svg width="40" height="40" viewBox="0 0 520 520" xmlns="http://www.w3.org/2000/svg">
                            <path d="m165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zm65.8-383.2c-138.7 0-244.8 105.3-244.8 244 0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1 100-33.2 167.8-128.1 167.8-239 0-138.7-112.5-244-251.2-244zm-147.6 344.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9s4.3 3.3 5.6 2.3c1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"></path>
                        </svg>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>